name: Tensor build checks

on:
  push:
   branches: [cmake]
  pull_request:
    branches: [cmake]

jobs:
  LinuxBuild:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install libraries
        run: sudo apt install -y libarpack2-dev libfftw3-dev googletest libgtest-dev ninja-build libopenblas-openmp-dev
      - name: fix permisions
        run: chmod u+x ./scripts/build-and-test.sh
      - name: configure
        run: ./scripts/build-and-test.sh --configure --sanitize --debug
      - name: build
        run: ./scripts/build-and-test.sh --build --threads=2
      - name: test
        run: ./scripts/build-and-test.sh --test --threads=2
        timeout-minutes: 10

  ClangTidy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install libraries
        run: sudo apt install -y libarpack2-dev libfftw3-dev googletest libgtest-dev ninja-build libopenblas-openmp-dev clang-tidy
      - name: fix permisions
        run: chmod u+x ./scripts/build-and-test.sh
      - name: configure
        run: ./scripts/build-and-test.sh --configure --sanitize --debug --clang-tidy
      - name: build
        run: ./scripts/build-and-test.sh --build --threads=2

  CppCheck:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install libraries
        run: sudo apt install -y libarpack2-dev libfftw3-dev googletest libgtest-dev ninja-build libopenblas-openmp-dev cppcheck
      - name: fix permisions
        run: chmod u+x ./scripts/build-and-test.sh
      - name: configure
        run: ./scripts/build-and-test.sh --configure --sanitize --debug --cppcheck
      - name: build
        run: ./scripts/build-and-test.sh --build --threads=2

  VisualStudioVcpkg64:
    runs-on: windows-latest
    if: ${{ false }}
    steps:
    - uses: actions/checkout@v2
    - name: install 64-bit libraries
      run: c:/vcpkg/vcpkg.exe install openblas[threads]:x64-windows fftw3:x64-windows lapack:x64-windows gtest:x64-windows
    - name: build
      run: ./scripts/build-and-test.cmd vs22-64 --fftw --clean --configure
    - name: build
      run: ./scripts/build-and-test.cmd vs22-64 --build
    - name: test
      run: ./scripts/build-and-test.cmd vs22-64 --test
      timeout-minutes: 10

  Msys2Ucrt64:
    runs-on: windows-latest
    env:
      MSYSTEM: UCRT64
    defaults:
      run:
        shell: msys2 {0}
    if: ${{ false }}
    steps:
    - name: Setup MSYS2-UCRT64
      uses: msys2/setup-msys2@v2
      with:
        update: false
        msystem: ucrt64
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-openblas
          mingw-w64-ucrt-x86_64-fftw
          mingw-w64-ucrt-x86_64-arpack
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: fix permisions
      run: chmod u+x ./scripts/build-and-test.sh
    - name: configure
      run: ./scripts/build-and-test.sh --configure --debug --no-fftw
    - name: build
      run: ./scripts/build-and-test.sh --build --threads=2
    - name: test
      run: ./scripts/build-and-test.sh --test --threads=2
      timeout-minutes: 10
