name: Tensor build checks

on:
  push:
    branches: [cmake]
  pull_request:
    branches: [cmake]

jobs:
  LinuxBuild:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install libraries
        run: sudo apt install -y libarpack2-dev libfftw3-dev googletest libgtest-dev ninja-build libopenblas-openmp-dev
      - name: fix permisions
        run: chmod u+x ./scripts/build-and-test.sh
      - name: configure
        run: ./scripts/build-and-test.sh --configure
      - name: build
        run: ./scripts/build-and-test.sh --build
      - name: test
        run: ./scripts/build-and-test.sh --test